# CI for Product Catalog Service
name: product-catalog-ci

on:
    pull_request:
        branches:
            - main
jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Go 1.22
          uses: actions/setup-go@v4
          with:
            go-version: 1.22

        - name: Build
          run: go build -o product-catalog-service src/product-catalog/main.go

        - name: Unit Tests
          run: go test ./src/product-catalog/...

    code-quality:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Run golangci-lint
          run: |
                  go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
                  golangci-lint run ./src/product-catalog/...

    docker:
      runs-on: ubuntu-latest
      needs: build

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Install Docker
          uses: docker/setup-buildx-action@v2

        - name: Log in to Docker
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
            